/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using ToyLanguage.node;
using ToyLanguage.lexer;
using ToyLanguage.analysis;

namespace ToyLanguage.parser {

public class ParserException : ApplicationException
{
    Token token;

    public ParserException(Token token, String  message) : base(message)
    {
        this.token = token;
    }

    public Token Token
    {
      get { return token; }
    }
}

internal class State
{
    internal int state;
    internal ArrayList nodes;

    internal State(int state, ArrayList nodes)
    {
        this.state = state;
        this.nodes = nodes;
    }
}

internal class TokenIndex : AnalysisAdapter
{
    internal int index;

    public override void CaseTAssign(TAssign node)
    {
        index = 0;
    }

    public override void CaseTPlus(TPlus node)
    {
        index = 1;
    }

    public override void CaseTMult(TMult node)
    {
        index = 2;
    }

    public override void CaseTMinus(TMinus node)
    {
        index = 3;
    }

    public override void CaseTDivide(TDivide node)
    {
        index = 4;
    }

    public override void CaseTEqual(TEqual node)
    {
        index = 5;
    }

    public override void CaseTGreaterEqual(TGreaterEqual node)
    {
        index = 6;
    }

    public override void CaseTLessEqual(TLessEqual node)
    {
        index = 7;
    }

    public override void CaseTGreater(TGreater node)
    {
        index = 8;
    }

    public override void CaseTLess(TLess node)
    {
        index = 9;
    }

    public override void CaseTAnd(TAnd node)
    {
        index = 10;
    }

    public override void CaseTOr(TOr node)
    {
        index = 11;
    }

    public override void CaseTNot(TNot node)
    {
        index = 12;
    }

    public override void CaseTConstant(TConstant node)
    {
        index = 13;
    }

    public override void CaseTIf(TIf node)
    {
        index = 14;
    }

    public override void CaseTElse(TElse node)
    {
        index = 15;
    }

    public override void CaseTWhile(TWhile node)
    {
        index = 16;
    }

    public override void CaseTVoid(TVoid node)
    {
        index = 17;
    }

    public override void CaseTLParenth(TLParenth node)
    {
        index = 18;
    }

    public override void CaseTRParenth(TRParenth node)
    {
        index = 19;
    }

    public override void CaseTMain(TMain node)
    {
        index = 20;
    }

    public override void CaseTEol(TEol node)
    {
        index = 21;
    }

    public override void CaseTId(TId node)
    {
        index = 22;
    }

    public override void CaseTInteger(TInteger node)
    {
        index = 23;
    }

    public override void CaseTFloat(TFloat node)
    {
        index = 24;
    }

    public override void CaseTString(TString node)
    {
        index = 25;
    }

    public override void CaseTChar(TChar node)
    {
        index = 26;
    }

    public override void CaseEOF(EOF node)
    {
        index = 27;
    }
}

public class Parser
{
    private Analysis ignoredTokens = new AnalysisAdapter();
    public Analysis IgnoredTokens
    {
      get { return ignoredTokens; }
    }

    protected ArrayList nodeList;

    private Lexer lexer;
    private Stack stack = new Stack();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private TokenIndex converter = new TokenIndex();
    private int[] action = new int[2];

    private const int SHIFT = 0;
    private const int REDUCE = 1;
    private const int ACCEPT = 2;
    private const int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    private int GoTo(int index)
    {
        int state = State();
        int low = 1;
        int high = gotoTable[index].Length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void Push(int numstate, ArrayList listNode)
    {
        this.nodeList = listNode;

        stack.Push(new State(numstate, this.nodeList));
    }

    private int State()
    {
        State s = (State) stack.Peek();
        return s.state;
    }

    private ArrayList Pop()
    {
        return (ArrayList) ((State) stack.Pop()).nodes;
    }

    private int Index(Switchable token)
    {
        converter.index = -1;
        token.Apply(converter);
        return converter.index;
    }

    public Start Parse()
    {
        Push(0, null);

        IList ign = null;
        while(true)
        {
            while(Index(lexer.Peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedList(NodeCast.Instance);
                }

                ign.Add(lexer.Next());
            }

            if(ign != null)
            {
                ignoredTokens.SetIn(lexer.Peek(), ign);
                ign = null;
            }

            last_pos = lexer.Peek().Pos;
            last_line = lexer.Peek().Line;
            last_token = lexer.Peek();

            int index = Index(lexer.Peek());
            action[0] = actionTable[State()][0][1];
            action[1] = actionTable[State()][0][2];

            int low = 1;
            int high = actionTable[State()].Length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[State()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[State()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[State()][middle][1];
                    action[1] = actionTable[State()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
        {
            ArrayList list = new ArrayList();
            list.Add(lexer.Next());
                        Push(action[1], list);
                        last_shift = action[1];
                    }
        break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0:
        {
      ArrayList list = New0();
      Push(GoTo(0), list);
        }
        break;
                    case 1:
        {
      ArrayList list = New1();
      Push(GoTo(1), list);
        }
        break;
                    case 2:
        {
      ArrayList list = New2();
      Push(GoTo(1), list);
        }
        break;
                    case 3:
        {
      ArrayList list = New3();
      Push(GoTo(1), list);
        }
        break;
                    case 4:
        {
      ArrayList list = New4();
      Push(GoTo(1), list);
        }
        break;
                    case 5:
        {
      ArrayList list = New5();
      Push(GoTo(2), list);
        }
        break;
                    case 6:
        {
      ArrayList list = New6();
      Push(GoTo(3), list);
        }
        break;
                    case 7:
        {
      ArrayList list = New7();
      Push(GoTo(4), list);
        }
        break;
                    case 8:
        {
      ArrayList list = New8();
      Push(GoTo(4), list);
        }
        break;
                    case 9:
        {
      ArrayList list = New9();
      Push(GoTo(4), list);
        }
        break;
                    case 10:
        {
      ArrayList list = New10();
      Push(GoTo(5), list);
        }
        break;
                    case 11:
        {
      ArrayList list = New11();
      Push(GoTo(6), list);
        }
        break;
                    case 12:
        {
      ArrayList list = New12();
      Push(GoTo(6), list);
        }
        break;
                    case 13:
        {
      ArrayList list = New13();
      Push(GoTo(7), list);
        }
        break;
                    case 14:
        {
      ArrayList list = New14();
      Push(GoTo(7), list);
        }
        break;
                    case 15:
        {
      ArrayList list = New15();
      Push(GoTo(8), list);
        }
        break;
                    case 16:
        {
      ArrayList list = New16();
      Push(GoTo(8), list);
        }
        break;
                    case 17:
        {
      ArrayList list = New17();
      Push(GoTo(8), list);
        }
        break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.Next();
                        PProgram node1 = (PProgram) ((ArrayList)Pop())[0];
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }

    ArrayList New0()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PStmts pstmtsNode2 = (PStmts)nodeArrayList1[0];
        AProgram pprogramNode1 = new AProgram (
              pstmtsNode2
        );
        nodeList.Add(pprogramNode1);
        return nodeList;
    }
    ArrayList New1()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PAssignment passignmentNode2 = (PAssignment)nodeArrayList1[0];
        AStmtsAssignmentStmts pstmtsNode1 = new AStmtsAssignmentStmts (
              passignmentNode2
        );
        nodeList.Add(pstmtsNode1);
        return nodeList;
    }
    ArrayList New2()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        AStmtsXprStmts pstmtsNode1 = new AStmtsXprStmts (
              pexpressionNode2
        );
        nodeList.Add(pstmtsNode1);
        return nodeList;
    }
    ArrayList New3()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PFunctioncall pfunctioncallNode2 = (PFunctioncall)nodeArrayList1[0];
        AStmtsFunctioncallStmts pstmtsNode1 = new AStmtsFunctioncallStmts (
              pfunctioncallNode2
        );
        nodeList.Add(pstmtsNode1);
        return nodeList;
    }
    ArrayList New4()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PDeclaration pdeclarationNode2 = (PDeclaration)nodeArrayList1[0];
        AStmtsDeclarationStmts pstmtsNode1 = new AStmtsDeclarationStmts (
              pdeclarationNode2
        );
        nodeList.Add(pstmtsNode1);
        return nodeList;
    }
    ArrayList New5()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList4 = (ArrayList) Pop();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TId tidNode2 = (TId)nodeArrayList1[0];
        TAssign tassignNode3 = (TAssign)nodeArrayList2[0];
        PExpression pexpressionNode4 = (PExpression)nodeArrayList3[0];
        TEol teolNode5 = (TEol)nodeArrayList4[0];
        AAssignment passignmentNode1 = new AAssignment (
              tidNode2,
              tassignNode3,
              pexpressionNode4,
              teolNode5
        );
        nodeList.Add(passignmentNode1);
        return nodeList;
    }
    ArrayList New6()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList5 = (ArrayList) Pop();
        ArrayList nodeArrayList4 = (ArrayList) Pop();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TId tidNode2 = (TId)nodeArrayList1[0];
        TLParenth tlparenthNode3 = (TLParenth)nodeArrayList2[0];
        PArguments pargumentsNode4 = (PArguments)nodeArrayList3[0];
        TRParenth trparenthNode5 = (TRParenth)nodeArrayList4[0];
        TEol teolNode6 = (TEol)nodeArrayList5[0];
        AFunctioncall pfunctioncallNode1 = new AFunctioncall (
              tidNode2,
              tlparenthNode3,
              pargumentsNode4,
              trparenthNode5,
              teolNode6
        );
        nodeList.Add(pfunctioncallNode1);
        return nodeList;
    }
    ArrayList New7()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TInteger tintegerNode2 = (TInteger)nodeArrayList1[0];
        AIntArgArguments pargumentsNode1 = new AIntArgArguments (
              tintegerNode2
        );
        nodeList.Add(pargumentsNode1);
        return nodeList;
    }
    ArrayList New8()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TFloat tfloatNode2 = (TFloat)nodeArrayList1[0];
        AFloatArgArguments pargumentsNode1 = new AFloatArgArguments (
              tfloatNode2
        );
        nodeList.Add(pargumentsNode1);
        return nodeList;
    }
    ArrayList New9()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TString tstringNode2 = (TString)nodeArrayList1[0];
        AStringArgArguments pargumentsNode1 = new AStringArgArguments (
              tstringNode2
        );
        nodeList.Add(pargumentsNode1);
        return nodeList;
    }
    ArrayList New10()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TId tidNode2 = (TId)nodeArrayList1[0];
        TId tidNode3 = (TId)nodeArrayList2[0];
        TEol teolNode4 = (TEol)nodeArrayList3[0];
        ADeclaration pdeclarationNode1 = new ADeclaration (
              tidNode2,
              tidNode3,
              teolNode4
        );
        nodeList.Add(pdeclarationNode1);
        return nodeList;
    }
    ArrayList New11()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        TPlus tplusNode3 = (TPlus)nodeArrayList2[0];
        PMultiPass pmultipassNode4 = (PMultiPass)nodeArrayList3[0];
        APlusMultiExprExpression pexpressionNode1 = new APlusMultiExprExpression (
              pexpressionNode2,
              tplusNode3,
              pmultipassNode4
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New12()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        PMultiPass pmultipassNode3 = (PMultiPass)nodeArrayList2[0];
        AMultExprExpression pexpressionNode1 = new AMultExprExpression (
              pexpressionNode2,
              pmultipassNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New13()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PMultiPass pmultipassNode2 = (PMultiPass)nodeArrayList1[0];
        TMult tmultNode3 = (TMult)nodeArrayList2[0];
        PSimpleton psimpletonNode4 = (PSimpleton)nodeArrayList3[0];
        AMultiPassMultMultiPass pmultipassNode1 = new AMultiPassMultMultiPass (
              pmultipassNode2,
              tmultNode3,
              psimpletonNode4
        );
        nodeList.Add(pmultipassNode1);
        return nodeList;
    }
    ArrayList New14()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PSimpleton psimpletonNode2 = (PSimpleton)nodeArrayList1[0];
        AMultiPassSimpletonMultiPass pmultipassNode1 = new AMultiPassSimpletonMultiPass (
              psimpletonNode2
        );
        nodeList.Add(pmultipassNode1);
        return nodeList;
    }
    ArrayList New15()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TId tidNode2 = (TId)nodeArrayList1[0];
        AVariableSimpletonSimpleton psimpletonNode1 = new AVariableSimpletonSimpleton (
              tidNode2
        );
        nodeList.Add(psimpletonNode1);
        return nodeList;
    }
    ArrayList New16()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TInteger tintegerNode2 = (TInteger)nodeArrayList1[0];
        AIntegerSimpletonSimpleton psimpletonNode1 = new AIntegerSimpletonSimpleton (
              tintegerNode2
        );
        nodeList.Add(psimpletonNode1);
        return nodeList;
    }
    ArrayList New17()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TFloat tfloatNode2 = (TFloat)nodeArrayList1[0];
        AFloatSimpletonSimpleton psimpletonNode1 = new AFloatSimpletonSimpleton (
              tfloatNode2
        );
        nodeList.Add(psimpletonNode1);
        return nodeList;
    }

    private static int[][][] actionTable = {
      new int[][] {
        new int[] {-1, 3, 0},
        new int[] {22, 0, 1},
      },
      new int[][] {
        new int[] {-1, 3, 1},
        new int[] {0, 0, 8},
        new int[] {18, 0, 9},
        new int[] {22, 0, 10},
      },
      new int[][] {
        new int[] {-1, 3, 2},
        new int[] {27, 2, -1},
      },
      new int[][] {
        new int[] {-1, 1, 0},
      },
      new int[][] {
        new int[] {-1, 1, 1},
      },
      new int[][] {
        new int[] {-1, 1, 3},
      },
      new int[][] {
        new int[] {-1, 1, 4},
      },
      new int[][] {
        new int[] {-1, 1, 2},
        new int[] {1, 0, 11},
        new int[] {22, 0, 12},
        new int[] {23, 0, 13},
        new int[] {24, 0, 14},
      },
      new int[][] {
        new int[] {-1, 3, 8},
      },
      new int[][] {
        new int[] {-1, 3, 9},
        new int[] {23, 0, 18},
        new int[] {24, 0, 19},
        new int[] {25, 0, 20},
      },
      new int[][] {
        new int[] {-1, 3, 10},
        new int[] {21, 0, 22},
      },
      new int[][] {
        new int[] {-1, 3, 11},
        new int[] {22, 0, 12},
        new int[] {23, 0, 13},
        new int[] {24, 0, 14},
      },
      new int[][] {
        new int[] {-1, 1, 15},
      },
      new int[][] {
        new int[] {-1, 1, 16},
      },
      new int[][] {
        new int[] {-1, 1, 17},
      },
      new int[][] {
        new int[] {-1, 1, 12},
        new int[] {2, 0, 24},
      },
      new int[][] {
        new int[] {-1, 1, 14},
      },
      new int[][] {
        new int[] {-1, 3, 17},
        new int[] {1, 0, 11},
        new int[] {21, 0, 25},
        new int[] {22, 0, 12},
        new int[] {23, 0, 13},
        new int[] {24, 0, 14},
      },
      new int[][] {
        new int[] {-1, 1, 7},
      },
      new int[][] {
        new int[] {-1, 1, 8},
      },
      new int[][] {
        new int[] {-1, 1, 9},
      },
      new int[][] {
        new int[] {-1, 3, 21},
        new int[] {19, 0, 26},
      },
      new int[][] {
        new int[] {-1, 1, 10},
      },
      new int[][] {
        new int[] {-1, 1, 11},
        new int[] {2, 0, 24},
      },
      new int[][] {
        new int[] {-1, 3, 24},
        new int[] {22, 0, 12},
        new int[] {23, 0, 13},
        new int[] {24, 0, 14},
      },
      new int[][] {
        new int[] {-1, 1, 5},
      },
      new int[][] {
        new int[] {-1, 3, 26},
        new int[] {21, 0, 28},
      },
      new int[][] {
        new int[] {-1, 1, 13},
      },
      new int[][] {
        new int[] {-1, 1, 6},
      },
    };

    private static int[][][] gotoTable  = {
      new int[][] {
        new int[] {-1, 2},
      },
      new int[][] {
        new int[] {-1, 3},
      },
      new int[][] {
        new int[] {-1, 4},
      },
      new int[][] {
        new int[] {-1, 5},
      },
      new int[][] {
        new int[] {-1, 21},
      },
      new int[][] {
        new int[] {-1, 6},
      },
      new int[][] {
        new int[] {-1, 7},
        new int[] {8, 17},
      },
      new int[][] {
        new int[] {-1, 15},
        new int[] {11, 23},
      },
      new int[][] {
        new int[] {-1, 16},
        new int[] {24, 27},
      },
    };

    private static String[] errorMessages = {
      "expecting: id",
      "expecting: ':=', '(', id",
      "expecting: EOF",
      "expecting: '+', id, integer, float, EOF",
      "expecting: ",
      "expecting: integer, float, string",
      "expecting: ';'",
      "expecting: id, integer, float",
      "expecting: '+', '*', ';', id, integer, float, EOF",
      "expecting: '+', ';', id, integer, float",
      "expecting: ')'",
    };

    private static int[] errors = {
      0, 1, 2, 2, 2, 2, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 
      8, 9, 10, 10, 10, 10, 2, 8, 7, 2, 6, 8, 2, 
    };
}
}
